# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift

before_install:
  - brew outdated xctool || brew upgrade xctool
  - carthage update

script:
  - xcodebuild -project "KeyboardKit.xcodeproj" -scheme "KeyboardKit" -sdk "iphonesimulator" | xcpretty -c
  - pod lib lint
  - fastlane test